name: 'Deploy Service'
description: 'Action to deploy services'
inputs:
  service-name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Env by Stage
      run: echo "bla bla bla"